// Date: 11/3/2013 1:50:49 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package dark.empire.weapons.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelLaserRifle extends ModelBase
{
    //fields
    ModelRenderer Grip;
    ModelRenderer body2;
    ModelRenderer Grip2;
    ModelRenderer guard;
    ModelRenderer barrel;
    ModelRenderer body4;
    ModelRenderer body5;
    ModelRenderer body6;
    ModelRenderer body7;
    ModelRenderer chamber;
    ModelRenderer barrelRid;
    ModelRenderer barrel2;
    ModelRenderer barrel3;
    ModelRenderer barrel4;
    ModelRenderer barrel5;
    ModelRenderer battery;
    ModelRenderer batteryClip;
    ModelRenderer batteryClip2;

    public ModelLaserRifle()
    {
        textureWidth = 64;
        textureHeight = 32;

        Grip = new ModelRenderer(this, 1, 1);
        Grip.addBox(0F, 0F, 0F, 2, 5, 2);
        Grip.setRotationPoint(0F, 19F, 0F);
        Grip.setTextureSize(64, 32);
        Grip.mirror = true;
        setRotation(Grip, 1.134464F, 0F, 0F);
        body2 = new ModelRenderer(this, 0, 0);
        body2.addBox(0F, 0F, 0F, 2, 1, 5);
        body2.setRotationPoint(0F, 18F, -3F);
        body2.setTextureSize(64, 32);
        body2.mirror = true;
        setRotation(body2, 0F, 0F, 0F);
        Grip2 = new ModelRenderer(this, 0, 0);
        Grip2.addBox(0F, 0F, 0F, 1, 5, 1);
        Grip2.setRotationPoint(0.5F, 19F, 0F);
        Grip2.setTextureSize(64, 32);
        Grip2.mirror = true;
        setRotation(Grip2, 1.047198F, 0F, 0F);
        guard = new ModelRenderer(this, 1, 26);
        guard.addBox(0F, 0F, 0F, 1, 2, 1);
        guard.setRotationPoint(0.5F, 19F, -2F);
        guard.setTextureSize(64, 32);
        guard.mirror = true;
        setRotation(guard, 0.4014257F, 0F, 0F);
        barrel = new ModelRenderer(this, 33, 17);
        barrel.addBox(-1F, 0F, 0F, 1, 1, 13);
        barrel.setRotationPoint(1.1F, 16F, -18.01F);
        barrel.setTextureSize(64, 32);
        barrel.mirror = true;
        setRotation(barrel, 0F, 0F, 0F);
        body4 = new ModelRenderer(this, 0, 0);
        body4.addBox(0F, 0F, 0F, 2, 3, 3);
        body4.setRotationPoint(0F, 17F, 2F);
        body4.setTextureSize(64, 32);
        body4.mirror = true;
        setRotation(body4, 0F, 0F, 0F);
        body5 = new ModelRenderer(this, 0, 11);
        body5.addBox(1.5F, 0F, 0F, 3, 4, 5);
        body5.setRotationPoint(-2F, 16.5F, 5F);
        body5.setTextureSize(64, 32);
        body5.mirror = true;
        setRotation(body5, -0.0698132F, 0F, 0F);
        body6 = new ModelRenderer(this, 0, 0);
        body6.addBox(-1.5F, 0F, 0F, 3, 2, 1);
        body6.setRotationPoint(1F, 16.1F, 1F);
        body6.setTextureSize(64, 32);
        body6.mirror = true;
        setRotation(body6, 0F, 0F, 0F);
        body7 = new ModelRenderer(this, 0, 11);
        body7.addBox(1.5F, 0F, 0F, 3, 4, 5);
        body7.setRotationPoint(-2F, 16.5F, 5F);
        body7.setTextureSize(64, 32);
        body7.mirror = true;
        setRotation(body7, 0.122173F, 0F, 0F);
        chamber = new ModelRenderer(this, 17, 7);
        chamber.addBox(-1.5F, 0F, 0F, 3, 3, 6);
        chamber.setRotationPoint(1F, 15.8F, -5.01F);
        chamber.setTextureSize(64, 32);
        chamber.mirror = true;
        setRotation(chamber, 0F, 0F, 0F);
        barrelRid = new ModelRenderer(this, 35, 0);
        barrelRid.addBox(-0.5F, 0F, 0F, 1, 1, 14);
        barrelRid.setRotationPoint(1F, 18F, -18.01F);
        barrelRid.setTextureSize(64, 32);
        barrelRid.mirror = true;
        setRotation(barrelRid, 0F, 0F, 0F);
        barrel2 = new ModelRenderer(this, 33, 17);
        barrel2.addBox(0F, 0F, 0F, 1, 1, 13);
        barrel2.setRotationPoint(0.9F, 16F, -18.01F);
        barrel2.setTextureSize(64, 32);
        barrel2.mirror = true;
        setRotation(barrel2, 0F, 0F, 0F);
        barrel3 = new ModelRenderer(this, 35, 0);
        barrel3.addBox(0F, 0F, 0F, 1, 1, 13);
        barrel3.setRotationPoint(0F, 17F, -17.01F);
        barrel3.setTextureSize(64, 32);
        barrel3.mirror = true;
        setRotation(barrel3, 0F, 0F, 0F);
        barrel4 = new ModelRenderer(this, 35, 0);
        barrel4.addBox(1F, 0F, 0F, 1, 1, 13);
        barrel4.setRotationPoint(0F, 17F, -17.01F);
        barrel4.setTextureSize(64, 32);
        barrel4.mirror = true;
        setRotation(barrel4, 0F, 0F, 0F);
        barrel5 = new ModelRenderer(this, 25, 18);
        barrel5.addBox(0.5F, 0F, 0F, 1, 1, 1);
        barrel5.setRotationPoint(0F, 17F, -17.5F);
        barrel5.setTextureSize(64, 32);
        barrel5.mirror = true;
        setRotation(barrel5, 0F, 0F, 0F);
        battery = new ModelRenderer(this, 17, 22);
        battery.addBox(-1.5F, 0F, 0F, 2, 2, 5);
        battery.setRotationPoint(4F, 16F, -4.5F);
        battery.setTextureSize(64, 32);
        battery.mirror = true;
        setRotation(battery, 0F, 0F, 0F);
        batteryClip = new ModelRenderer(this, 17, 0);
        batteryClip.addBox(-1.5F, 0F, 0F, 2, 1, 1);
        batteryClip.setRotationPoint(3.6F, 16.5F, 0F);
        batteryClip.setTextureSize(64, 32);
        batteryClip.mirror = true;
        setRotation(batteryClip, 0F, 0F, 0F);
        batteryClip2 = new ModelRenderer(this, 17, 0);
        batteryClip2.addBox(-1.5F, 0F, 0F, 2, 1, 1);
        batteryClip2.setRotationPoint(3.6F, 16.5F, -5F);
        batteryClip2.setTextureSize(64, 32);
        batteryClip2.mirror = true;
        setRotation(batteryClip2, 0F, 0F, 0F);
    }

    public void render(float f5)
    {
        Grip.render(f5);
        body2.render(f5);
        Grip2.render(f5);
        guard.render(f5);
        barrel.render(f5);
        body4.render(f5);
        body5.render(f5);
        body6.render(f5);
        body7.render(f5);
        chamber.render(f5);
        barrelRid.render(f5);
        barrel2.render(f5);
        barrel3.render(f5);
        barrel4.render(f5);
        barrel5.render(f5);
        battery.render(f5);
        batteryClip.render(f5);
        batteryClip2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

}
